### ISSUE TITLE
"gme_delete" results in "RuntimeError: Aborted(segmentation fault)"

### ISSUE THREAD

**Issue by Thysbelon** [Thysbelon/Web-GME-Player#1]
To recreate, please download the broken branch, host it on a local testing server, and run with these settings:
song: 180.sap
length: 3000
worker: false
loop: no

error happens when the line "gme_delete" is reached in main.c

**Comment by Thysbelon** [comment]
After compiling with SAFE_HEAP, the error now says `Aborted(segmentation fault)`

**Comment by Thysbelon** [comment]
UBsan did not seem to give any extra information. Tomorrow I will try ASan.

**Comment by Thysbelon** [comment]
ASan seemed to have an error at a different part
```
================================================================= [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
==42==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x14d02500 at pc 0x000e88a1 bp 0x129c32a0 sp 0x129c32ac [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
READ of size 2 at 0x14d02500 thread T0 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #0 0xe88a1 in _asan_c_load_2 system/lib/asan_js.c:34:10 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #1 0x8000010e in _asan_js_load_2 http://localhost:8000/Web-GME-PlayerO0-ASan.js:270:33 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #2 0x80000449 in getValue http://localhost:8000/Web-GME-PlayerO0-ASan.js:1097:10 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #3 0x800000d5 in addBufferToSampleArray http://localhost:8000/gmeplay-function.js:213:47 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #4 0x800000cb in genGMEbuffers http://localhost:8000/gmeplay-function.js:203:20 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #5 0x800000b0 in GMEgenSamples http://localhost:8000/gmeplay-function.js:176:16 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #6 0x80000065 in internalGMEplay/< http://localhost:8000/gmeplay-function.js:101:17 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #7 0x80000039 in promise callback*internalGMEplay http://localhost:8000/gmeplay-function.js:57:52 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #8 0x80000021 in gmeplay http://localhost:8000/gmeplay-function.js:33:17 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #9 0x80000080 in myclick http://localhost:8000/:128:10 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #10 0x8000005d in EventListener.handleEvent* http://localhost:8000/:93:12 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
<empty string> [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
0x14d02500 is located 0 bytes after 4096-byte region [0x14d01500,0x14d02500) [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
allocated by thread T0 here: [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #0 0xceccc in malloc system/lib/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #1 0xb169a in setupMusStereo main.c:74:8 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #2 0x80000247 in createExportWrapper/< http://localhost:8000/Web-GME-PlayerO0-ASan.js:583:12 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #3 0x80001164 in ccall http://localhost:8000/Web-GME-PlayerO0-ASan.js:4452:17 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #4 0x8000003c in internalGMEplay/< http://localhost:8000/gmeplay-function.js:60:24 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #5 0x80000039 in promise callback*internalGMEplay http://localhost:8000/gmeplay-function.js:57:52 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #6 0x80000021 in gmeplay http://localhost:8000/gmeplay-function.js:33:17 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #7 0x80000080 in myclick http://localhost:8000/:128:10 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
    #8 0x8000005d in EventListener.handleEvent* http://localhost:8000/:93:12 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
<empty string> [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
SUMMARY: AddressSanitizer: heap-buffer-overflow system/lib/asan_js.c:34:10 in _asan_c_load_2 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
Shadow bytes around the buggy address: [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
=>0x14d02500:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02580: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02600: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02680: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  0x14d02780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
Shadow byte legend (one shadow byte represents 8 application bytes): [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Addressable:           00 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Partially addressable: 01 02 03 04 05 06 07 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Heap left redzone:       fa [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Freed heap region:       fd [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Stack left redzone:      f1 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Stack mid redzone:       f2 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Stack right redzone:     f3 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Stack after return:      f5 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Stack use after scope:   f8 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Global redzone:          f9 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Global init order:       f6 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Poisoned by user:        f7 [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Container overflow:      fc [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Array cookie:            ac [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Intra object redzone:    bb [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  ASan internal:           fe [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Left alloca redzone:     ca [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
  Right alloca redzone:    cb [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
==42==ABORTING [Web-GME-PlayerO0-ASan.js:1603:8](http://localhost:8000/Web-GME-PlayerO0-ASan.js)
Uncaught (in promise) 
Object { name: "ExitStatus", message: "Program terminated with exit(1)", status: 1 }
```

**Comment by Thysbelon** [comment]
I believe I have fixed this critical issue. The commits of the experimental branch will not be merged into main yet because Web Worker functionality is still broken.
